# Not the correct language, but one that has very few dependancies to install
language: c

before_script:
    - sudo apt-get update
    - sudo make build-deps

script:
    - make test
    - make test.extracted
